name: wpfamilylastseen
description: A Whatsapp Viewer App.


publish_to: 'none'


version: 1.0.3+12

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_clean_architecture: ^5.0.3
  iconify_flutter: ^0.0.5
  flag: ^6.0.0
  fluttertoast: ^8.1.1
  url_launcher: ^6.1.6
  country_pickers: ^2.0.0
  intl: ^0.17.0
  provider: ^6.0.4
  country_codes: ^2.2.0
  language_picker: ^0.4.1
  device_info_plus: ^8.0.0
  shared_preferences: ^2.0.15  
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  grock: ^0.0.9+4
  flutter_local_notifications: ^12.0.4
  pay: ^1.0.11
  easy_localization: ^3.0.1
  another_flushbar: ^1.12.29
  in_app_purchase: ^3.1.0
  in_app_purchase_storekit: ^0.3.4
  platform_device_id: ^1.0.1
  path_provider: ^2.0.11
  connectivity_plus: ^2.3.5
  syncfusion_flutter_charts: ^20.4.38
  lottie: ^2.1.0
  flutter_native_timezone: ^2.0.0
  eventify: ^1.0.1
  flutter_spinkit: ^5.1.0
  package_info_plus: ^3.0.1

  

easy_localization_loader: 
  git: https://github.com/sribuu/easy_localization_loader.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0

  


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/launcher_icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/launcher_icon.png"
    icon_size: 48

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

 